import { keyBy } from 'es-toolkit';

interface HabitIcon {
	iconTitle: string;
	category: string;
	icon: string;
}

export const HABIT_ICONS: HabitIcon[] = [
	// Featured
	{ iconTitle: 'mdi:record-circle-outline', category: 'featured', icon: 'mdi:record-circle-outline' },
	{ iconTitle: 'mdi:star-outline', category: 'featured', icon: 'mdi:star-outline' },
	{ iconTitle: 'mdi:weather-sunny', category: 'featured', icon: 'mdi:weather-sunny' },
	{ iconTitle: 'mdi:water', category: 'featured', icon: 'mdi:water' },
	{ iconTitle: 'mdi:fire', category: 'featured', icon: 'mdi:fire' },
	{ iconTitle: 'mdi:meditation', category: 'featured', icon: 'mdi:meditation' },
	{ iconTitle: 'material-symbols:self-improvement', category: 'featured', icon: 'material-symbols:self-improvement' },
	{ iconTitle: 'mdi:walk', category: 'featured', icon: 'mdi:walk' },
	{ iconTitle: 'mdi:run', category: 'featured', icon: 'mdi:run' },
	{ iconTitle: 'mdi:book-open-variant', category: 'featured', icon: 'mdi:book-open-variant' },
	{ iconTitle: 'mdi:translate', category: 'featured', icon: 'mdi:translate' },
	{ iconTitle: 'mdi:smoking-off', category: 'featured', icon: 'mdi:smoking-off' },
	{ iconTitle: 'mdi:bottle-wine-outline', category: 'featured', icon: 'mdi:bottle-wine-outline' },
	{ iconTitle: 'mdi:coffee', category: 'featured', icon: 'mdi:coffee' },
	{ iconTitle: 'mdi:leaf', category: 'featured', icon: 'mdi:leaf' },
	{ iconTitle: 'mdi:target', category: 'featured', icon: 'mdi:target' },
	{ iconTitle: 'mdi:alert-circle-outline', category: 'featured', icon: 'mdi:alert-circle-outline' },
	{ iconTitle: 'mdi:check-circle-outline', category: 'featured', icon: 'mdi:check-circle-outline' },
	{ iconTitle: 'mdi:calendar-check', category: 'featured', icon: 'mdi:calendar-check' },
	{ iconTitle: 'mdi:trophy-outline', category: 'featured', icon: 'mdi:trophy-outline' },
	{ iconTitle: 'mdi:lightbulb-outline', category: 'featured', icon: 'mdi:lightbulb-outline' },
	{ iconTitle: 'mdi:rocket-launch-outline', category: 'featured', icon: 'mdi:rocket-launch-outline' },
	{ iconTitle: 'mdi:party-popper', category: 'featured', icon: 'mdi:party-popper' },
	{ iconTitle: 'mdi:flag-outline', category: 'featured', icon: 'mdi:flag-outline' },
	{ iconTitle: 'mdi:trending-up', category: 'featured', icon: 'mdi:trending-up' },
	{ iconTitle: 'mdi:refresh', category: 'featured', icon: 'mdi:refresh' },

	// Sport
	{ iconTitle: 'mdi:bike', category: 'sport', icon: 'mdi:bike' },
	{ iconTitle: 'mdi:swim', category: 'sport', icon: 'mdi:swim' },
	{ iconTitle: 'mdi:boxing-glove', category: 'sport', icon: 'mdi:boxing-glove' },
	{ iconTitle: 'mdi:hiking', category: 'sport', icon: 'mdi:hiking' },
	{ iconTitle: 'mdi:skateboard', category: 'sport', icon: 'mdi:skateboard' },
	{ iconTitle: 'mdi:snowboard', category: 'sport', icon: 'mdi:snowboard' },
	{ iconTitle: 'mdi:basketball', category: 'sport', icon: 'mdi:basketball' },
	{ iconTitle: 'mdi:bowling', category: 'sport', icon: 'mdi:bowling' },
	{ iconTitle: 'mdi:soccer', category: 'sport', icon: 'mdi:soccer' },
	{ iconTitle: 'mdi:football', category: 'sport', icon: 'mdi:football' },
	{ iconTitle: 'mdi:table-tennis', category: 'sport', icon: 'mdi:table-tennis' },
	{ iconTitle: 'mdi:human-handsup', category: 'sport', icon: 'mdi:human-handsup' },
	{ iconTitle: 'mdi:arm-flex', category: 'sport', icon: 'mdi:arm-flex' },
	{ iconTitle: 'mdi:dumbbell', category: 'sport', icon: 'mdi:dumbbell' },
	{ iconTitle: 'mdi:run-fast', category: 'sport', icon: 'mdi:run-fast' },
	{ iconTitle: 'mdi:weight-lifter', category: 'sport', icon: 'mdi:weight-lifter' },
	{ iconTitle: 'mdi:yoga', category: 'sport', icon: 'mdi:yoga' },
	{ iconTitle: 'mdi:jump-rope', category: 'sport', icon: 'mdi:jump-rope' },
	{ iconTitle: 'mdi:rollerblade', category: 'sport', icon: 'mdi:rollerblade' },
	{ iconTitle: 'mdi:golf', category: 'sport', icon: 'mdi:golf' },
	{ iconTitle: 'mdi:baseball', category: 'sport', icon: 'mdi:baseball' },
	{ iconTitle: 'mdi:tennis', category: 'sport', icon: 'mdi:tennis' },
	{ iconTitle: 'mdi:volleyball', category: 'sport', icon: 'mdi:volleyball' },
	{ iconTitle: 'mdi:badminton', category: 'sport', icon: 'mdi:badminton' },
	{ iconTitle: 'mdi:ice-skate', category: 'sport', icon: 'mdi:ice-skate' },
	{ iconTitle: 'mdi:karate', category: 'sport', icon: 'mdi:karate' },
	{ iconTitle: 'mdi:pole-vault', category: 'sport', icon: 'mdi:pole-vault' },
	{ iconTitle: 'mdi:rowing', category: 'sport', icon: 'mdi:rowing' },

	// Education
	{ iconTitle: 'mdi:book-open-page-variant-outline', category: 'education', icon: 'mdi:book-open-page-variant-outline' },
	{ iconTitle: 'mdi:pencil', category: 'education', icon: 'mdi:pencil' },
	{ iconTitle: 'mdi:school-outline', category: 'education', icon: 'mdi:school-outline' },
	{ iconTitle: 'mdi:television', category: 'education', icon: 'mdi:television' },
	{ iconTitle: 'mdi:keyboard', category: 'education', icon: 'mdi:keyboard' },
	{ iconTitle: 'mdi:graduation-cap', category: 'education', icon: 'mdi:graduation-cap' },
	{ iconTitle: 'mdi:chess-knight', category: 'education', icon: 'mdi:chess-knight' },
	{ iconTitle: 'mdi:music-note', category: 'education', icon: 'mdi:music-note' },
	{ iconTitle: 'mdi:palette', category: 'education', icon: 'mdi:palette' },
	{ iconTitle: 'mdi:code-tags', category: 'education', icon: 'mdi:code-tags' },
	{ iconTitle: 'mdi:currency-usd', category: 'education', icon: 'mdi:currency-usd' },
	{ iconTitle: 'mdi:briefcase-outline', category: 'education', icon: 'mdi:briefcase-outline' },
	{ iconTitle: 'mdi:guitar-acoustic', category: 'education', icon: 'mdi:guitar-acoustic' },
	{ iconTitle: 'mdi:pen', category: 'education', icon: 'mdi:pen' },
	{ iconTitle: 'mdi:music', category: 'education', icon: 'mdi:music' },
	{ iconTitle: 'mdi:microphone', category: 'education', icon: 'mdi:microphone' },
	{ iconTitle: 'mdi:camera', category: 'education', icon: 'mdi:camera' },
	{ iconTitle: 'mdi:book-multiple', category: 'education', icon: 'mdi:book-multiple' },
	{ iconTitle: 'mdi:math-compass', category: 'education', icon: 'mdi:math-compass' },
	{ iconTitle: 'mdi:atom', category: 'education', icon: 'mdi:atom' },
	{ iconTitle: 'mdi:head-lightbulb-outline', category: 'education', icon: 'mdi:head-lightbulb-outline' },
	{ iconTitle: 'mdi:library', category: 'education', icon: 'mdi:library' },
	{ iconTitle: 'mdi:language-html5', category: 'education', icon: 'mdi:language-html5' },
	{ iconTitle: 'mdi:language-python', category: 'education', icon: 'mdi:language-python' },
	{ iconTitle: 'mdi:language-javascript', category: 'education', icon: 'mdi:language-javascript' },
	{ iconTitle: 'mdi:abacus', category: 'education', icon: 'mdi:abacus' },
	{ iconTitle: 'mdi:globe-model', category: 'education', icon: 'mdi:globe-model' },
	{ iconTitle: 'mdi:flask-outline', category: 'education', icon: 'mdi:flask-outline' },

	// Health
	{ iconTitle: 'mdi:medical-bag', category: 'health', icon: 'mdi:medical-bag' },
	{ iconTitle: 'mdi:heart', category: 'health', icon: 'mdi:heart' },
	{ iconTitle: 'mdi:heart-pulse', category: 'health', icon: 'mdi:heart-pulse' },
	{ iconTitle: 'mdi:pill', category: 'health', icon: 'mdi:pill' },
	{ iconTitle: 'mdi:needle', category: 'health', icon: 'mdi:needle' },
	{ iconTitle: 'mdi:brain', category: 'health', icon: 'mdi:brain' },
	{ iconTitle: 'mdi:tooth', category: 'health', icon: 'mdi:tooth' },
	{ iconTitle: 'mdi:stethoscope', category: 'health', icon: 'mdi:stethoscope' },
	{ iconTitle: 'mdi:food-apple', category: 'health', icon: 'mdi:food-apple' },
	{ iconTitle: 'mdi:food-apple-outline', category: 'health', icon: 'mdi:food-apple-outline' },
	{ iconTitle: 'mdi:carrot', category: 'health', icon: 'mdi:carrot' },
	{ iconTitle: 'mdi:food-drumstick-outline', category: 'health', icon: 'mdi:food-drumstick-outline' },
	{ iconTitle: 'mdi:water-outline', category: 'health', icon: 'mdi:water-outline' },
	{ iconTitle: 'mdi:coffee-outline', category: 'health', icon: 'mdi:coffee-outline' },
	{ iconTitle: 'mdi:bed', category: 'health', icon: 'mdi:bed' },
	{ iconTitle: 'mdi:food', category: 'health', icon: 'mdi:food' },
	{ iconTitle: 'mdi:run-fast', category: 'health', icon: 'mdi:run-fast' },
	{ iconTitle: 'mdi:weight-lifter', category: 'health', icon: 'mdi:weight-lifter' },
	{ iconTitle: 'mdi:meditation', category: 'health', icon: 'mdi:meditation' },
	{ iconTitle: 'mdi:scale-bathroom', category: 'health', icon: 'mdi:scale-bathroom' },
	{ iconTitle: 'mdi:bone', category: 'health', icon: 'mdi:bone' },
	{ iconTitle: 'mdi:eye-outline', category: 'health', icon: 'mdi:eye-outline' },
	{ iconTitle: 'mdi:ear-hearing', category: 'health', icon: 'mdi:ear-hearing' },
	{ iconTitle: 'mdi:lungs', category: 'health', icon: 'mdi:lungs' },
	{ iconTitle: 'mdi:tooth-outline', category: 'health', icon: 'mdi:tooth-outline' },
	{ iconTitle: 'mdi:blood-bag', category: 'health', icon: 'mdi:blood-bag' },
	{ iconTitle: 'mdi:thermometer', category: 'health', icon: 'mdi:thermometer' },
	{ iconTitle: 'mdi:hospital-box-outline', category: 'health', icon: 'mdi:hospital-box-outline' },
];

export const HABIT_ICONS_MAP = keyBy(HABIT_ICONS, (icon) => icon.iconTitle);
